on:
  # This workflow will only run on PRs containing .md changes
  pull_request_target:
    paths:
      - "**.md"
  pull_request:
    types:
      - closed

jobs:
  get-md-files:
    runs-on: ubuntu-latest
    outputs:
      md_files: ${{ steps.get_md_files.outputs.md_files }}
    steps:
      - name: Get Changed Markdown File Names
        id: get_md_files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          eval FILES=\($(curl -s -X GET -G $URL | jq '.[].filename')\)
          echo "# Filename Aggregation Complete" >> $GITHUB_STEP_SUMMARY
          echo "## Markdown Files" >> $GITHUB_STEP_SUMMARY
          echo "Markdown files (.md) in this pull request:" >> $GITHUB_STEP_SUMMARY
          MD_FILENAMES=""
          for filename in "${FILES[@]}"
          do
            if [[ $filename == *\.md ]]
            then
              echo "* $filename" >> $GITHUB_STEP_SUMMARY
              MD_FILENAMES="$MD_FILENAMES$filename,"
            fi 
          done
          if [[ $MD_FILENAMES == "" ]]
          then
            echo "* No .md files were updated in this PR." >> $GITHUB_STEP_SUMMARY
          fi
          echo "::set-output name=md_files::$MD_FILENAMES"
  # "Deploys" to dev environment
  # make manual
  #deploy-dev:
  #runs-on: 'ubuntu-latest'
  #environment: 'dev'
  #steps:
  #- run: echo "dev is deployed"

  # "Deploys" to staging environment
  deploy-qa:
    if: ${{needs.get-md-files.outputs.md_files}} && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: "qa"
    needs: [get-md-files]
    steps:
      - name: AEM Injestion - Staging
        id: aem_injestion_qa
        run: curl -X GET -s -S https://raw.githubusercontent.com/rbitting/testing/master/.github/workflows/scripts/aem-injestion.sh | bash -s -- qa "${{needs.get-md-files.outputs.md_files}}"

  # "Deploys" to prod environment
  # In environment settings of repo, be sure that prod has reviewers assigned
  deploy-prod:
    if: ${{needs.get-md-files.outputs.md_files}} && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: "prod"
    needs: [get-md-files, deploy-qa]
    steps:
      - name: AEM Injestion - Production
        id: aem_injestion_prod
        run: curl -X GET -s -S https://raw.githubusercontent.com/rbitting/testing/master/.github/workflows/scripts/aem-injestion.sh | bash -s -- prod "${{needs.get-md-files.outputs.md_files}}"
