on:
  pull_request_target:
    paths:
      - '**.md'
  pull_request:
    types:
      - closed

# TODO: verify md files affected
jobs:
  # "Deploys" to dev environment
  #deploy-dev:
    #runs-on: 'ubuntu-latest'
    #environment: 'dev'
    #steps:
      #- run: echo "dev is deployed"

  # "Deploys" to staging environment
  deploy-qa:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: 'qa'
    needs: [deploy-dev]
    steps:
    - name: Set Job Summary
      id: set_job_summary
      run: |
        echo "### QA deploy" >> $GITHUB_STEP_SUMMARY
        echo "URL path retrieved from dummy endpoint: " >> $GITHUB_STEP_SUMMARY
        ENDPOINT_DATA=$(curl -X GET -s -S "https://developer.twitter.com/en.useful-links.json") && echo $ENDPOINT_DATA && echo $ENDPOINT_DATA | jq --raw-output '.publishUrl' >> $GITHUB_STEP_SUMMARY

  # "Deploys" to prod environment
  # In environment settings of repo, be sure that prod has reviewers assigned
  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [deploy-dev, deploy-qa]
    steps:
      - run: echo "### Prod deploy" >> $GITHUB_STEP_SUMMARY
