on:
  pull_request_target:
    paths:
      - '**.md'
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "The .md PR was merged"

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [if_merged]
    steps:
      - run: echo "Prod is deployed"
